# Generated by Django 4.1.1 on 2022-10-02 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='color_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Color groups',
                'db_table': 'bt_color_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='breakthrough.color_group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'bt_member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now=True)),
                ('purchase_amount', models.IntegerField()),
                ('purchase_ref', models.CharField(max_length=150)),
                ('verified_on', models.DateField(auto_now=True)),
                ('transaction_ref', models.CharField(max_length=150)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_share', to='breakthrough.member')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shares',
                'db_table': 'bt_shares',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('request_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CANCELLED', 'Cancelled'), ('PROGRESS', 'On Progress'), ('COMPLETE', 'Complete')], default='NEW', max_length=14)),
                ('verified_on', models.DateField(auto_now=True)),
                ('transaction_ref', models.CharField(max_length=150)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_loan', to='breakthrough.member')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loans',
                'db_table': 'bt_loans',
                'managed': True,
            },
        ),
    ]
