# Generated by Django 4.1.1 on 2022-10-02 18:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breakthrough', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan',
            new_name='Loans',
        ),
    ]
