# Generated by Django 4.1.1 on 2022-10-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakthrough', '0002_rename_loan_loans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='title',
        ),
    ]
