# Generated by Django 4.1.1 on 2022-10-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakthrough', '0003_remove_member_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='account_bank',
            field=models.CharField(default='NONE', max_length=50, verbose_name='account_bank'),
        ),
        migrations.AddField(
            model_name='member',
            name='account_name',
            field=models.CharField(default='NONE', max_length=50, verbose_name='account_name'),
        ),
        migrations.AddField(
            model_name='member',
            name='account_number',
            field=models.CharField(default='000000000', max_length=50, verbose_name='account_number'),
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='Dar-es-Salaam', max_length=50, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(default='1900-01-01', verbose_name='date_of_birth'),
        ),
        migrations.AddField(
            model_name='member',
            name='id_number',
            field=models.CharField(default='00000000-00000-000000', max_length=50, verbose_name='id_number'),
        ),
        migrations.AddField(
            model_name='member',
            name='id_type',
            field=models.CharField(choices=[('NIDA', 'National ID'), ('PASSPORT', 'Passport')], default='NIDA', max_length=10, verbose_name='id_type'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(default='0700000000', max_length=50, verbose_name='phone_number'),
        ),
    ]
